### ISSUE TITLE
[BUG] Can't upload shop image or banner

### ISSUE THREAD

**Issue by auggie-lahey** [shopstr-eng/shopstr#215]
### Description

Cannot read properties of undefined (reading 'toString')
should also make it so the user can just paste in the URL and not have to upload. my image is already on blossom

### Current Behavior

can't upload image

### Expected Behavior

image upload succeeded

### Steps to Reproduce

login to amber
go to shop profile and try to upload image

### Next.js Version

na

### Operating System

Linux (Other)

### Node.js Version

na

### Browser

Other

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by GautamBytes** [comment]
closing as fixed by #229

**Comment by emmedigitnet** [comment]
On shopstr 0.7.5 (in my case on Umbrel OS) the problem still remains; no upload possible to product image and to shop image. Is it possible to reopen this issue? Tried with different blossom...
Directly on shopstr.market I succeded...

**Comment by GautamBytes** [comment]
will try to reproduce it and get back to u, reopening for now

**Comment by GautamBytes** [comment]
@emmedigitnet can u try now , we made a fix for this yesterday and it seems to work fine on our end now!

**Comment by emmedigitnet** [comment]
Hi,
I'm gonna try but I think I've to wait for Shopstr App update on Umbrel
isn't it?
I've no updates for now. I'll tell you asap.
Thanks

Il giorno lun 14 set 2026 alle ore 16:05 Gautam Manchandani <
***@***.***> ha scritto:

**Comment by GautamBytes** [comment]
I think calva did yesterday cc @calvadev

**Comment by emmedigitnet** [comment]
Hi.
Still no update of shopstr on Umbrel.



Il giorno lun 14 set 2026 alle ore 16:36 Gautam Manchandani <
***@***.***> ha scritto:

**Comment by calvadev** [comment]
Ah, this is Umbre specific, my mistake. Will bump the images and submit for review on the app store for it. @emmedigitnet
